### ISSUE TITLE
Recaptcha Breaks 2FA

### ISSUE THREAD

**Issue by rogueops** [sjinks/roundcube_recaptcha#6]
Have had 2FA installed for quite some time with no issues. After installing recaptcha, it shows up on the login page and then when entering login it just goes to a blank page. When disabling the recaptcha plugin and just refreshing the page the 2FA code page shows up and then loads the email. Created identical ticket with 2FA plugin as I do not know which is breaking which as each on their own works.

**Comment by sjinks** [comment]
Hello,Is there any error in the logs?Which 2FA plugin do you use? We use twofactor_gauthenticator, this combination works for us.7 апр. 2019 г. 23:04 пользователь gh0stshell <notifications@github.com> написал:Have had 2FA installed for quite some time with no issues. After installing recaptcha, it shows up on the login page and then when entering login it just goes to a blank page. When disabling the recaptcha plugin and just refreshing the page the 2FA code page shows up and then loads the email. Created identical ticket with 2FA plugin as I do not know which is breaking which as each on their own works.

**Comment by rogueops** [comment]
It is definitely the recaptcha plugin, if I remove all other plugins and
leave just that one when I tried to login it goes to a white page with no
errors in the mail.err log or mail.log or on the screen. If I remove
recaptcha and turn all plugins back on i can login with an account that has
2FA setup and one that does not. The issue is when having recaptcha enabled
after entering the email and password it just goes to a blank white page
with no errors.

**Comment by 1kUHuiswkvj7spRO** [comment]
What version of `PHP` are you running?
What do your `PHP` error log files say? Nothing would be in `mail.err` or `mail.log`, as that usually pertains to the internal mail system.

**Comment by rogueops** [comment]
On my server i have custom logs and all roundcube and mail get dumped into
those 2 logs so yes there would be stuff in there.

PHP 7.3.3

When checking the web server logs after turning them up 2 levels I now get:

PHP Fatal error:  Uncaught Error: Class 'ReCaptcha\ReCaptcha' not found in
/etc/roundcube/plugins/recaptcha/recaptcha.php:39
Stack trace:
#0  /etc/roundcube/rcube_plugin_api.php(440): recaptcha->authenticate(Array)
#1 /etc/roundcube/index.php(112):
rcube_plugin_api->exec_hook('authenticate', Array)
#2 {main}
  thrown in /etc/roundcube/plugins/recaptcha/recaptcha.php on line 39

**Comment by 1kUHuiswkvj7spRO** [comment]
This sounds like a required dependency was not satisfied:
`"google/recaptcha": "^1.1"`

Did you install this plugin with composer?

If so, run
`php composer.phar show`

and ensure this line exists:
`...
google/recaptcha                            1.2.1              Client library for reCAPTCHA, a free service that protects websites from spam and abuse.
...
`

**Comment by rogueops** [comment]
Per Getting started since you did not mention anything specifically i did
what it listed which was:

php composer.phar install

Should I dod it again, i ran this while inside the recaptcha folder.

**Comment by booshlinux** [comment]
Typically the composer.phar file is in the root of your round cube directory.

**Comment by 1kUHuiswkvj7spRO** [comment]
I should of been more specific, The `php composer.phar show` command should be run within the root directory of your roundcube installation.
